import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// Custom fonts from fonts folder
const clashGroteskRegular = localFont({
    src: "../../public/fonts/ClashGrotesk-Regular.otf",
    variable: "--font-clash-grotesk-regular",
});

const clashGroteskMedium = localFont({
    src: "../../public/fonts/ClashGrotesk-Medium.otf",
    variable: "--font-clash-grotesk-medium",
});

const sofiaSansRegular = localFont({
    src: "../../public/fonts/SofiaSans-Regular.ttf",
    variable: "--font-sofia-sans-regular",
});

const sofiaSansMedium = localFont({
    src: "../../public/fonts/SofiaSans-Medium.ttf",
    variable: "--font-sofia-sans-medium",
});

const sofiaSansItalic = localFont({
    src: "../../public/fonts/SofiaSans-Italic.ttf",
    variable: "--font-sofia-sans-italic",
});

const sofiaSansMediumItalic = localFont({
    src: "../../public/fonts/SofiaSans-MediumItalic.ttf",
    variable: "--font-sofia-sans-medium-italic",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${clashGroteskRegular.variable} ${clashGroteskMedium.variable} ${sofiaSansRegular.variable} ${sofiaSansMedium.variable} ${sofiaSansItalic.variable} ${sofiaSansMediumItalic.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
